# SAM Configuration File
version = 0.1

[default.global.parameters]
stack_name = "task-manager-backend"  # Fixed typo from "taks" to "task"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"  # Added CAPABILITY_NAMED_IAM
confirm_changeset = false
resolve_s3 = false
s3_prefix = "task-manager-backend"
region = "eu-central-1"
#profile = "dev-profile"
parameter_overrides = "Environment=\"Production\""  # Added environment parameter
image_repositories = []

[default.package.parameters]
resolve_s3 = false

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"