AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Task Management System - Parent Stack

Resources:
  SnsSqsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: sns-sqs-template.yaml
      Tags:
        - Key: Component
          Value: SNS-SQS

  StepFunctionsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: SnsSqsStack
    Properties:
      TemplateURL: step-functions-template.yaml
      Parameters:
        TaskAssignmentNotificationTopicArn: !GetAtt SnsSqsStack.Outputs.TaskAssignmentNotificationTopicArn
        TaskDeadlineNotificationTopicArn: !GetAtt SnsSqsStack.Outputs.TaskDeadlineNotificationTopicArn
        ClosedTasksNotificationTopicArn: !GetAtt SnsSqsStack.Outputs.ClosedTasksNotificationTopicArn
      Tags:
        - Key: Component
          Value: StepFunctions

  CognitoStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - SnsSqsStack
      - StepFunctionsStack
    Properties:
      TemplateURL: cognito-template.yaml
      Parameters:
        TeamMemberSubscriptionStepFunctionArn: !GetAtt StepFunctionsStack.Outputs.TeamMemberSubscriptionStepFunctionArn
        TaskAssignmentNotificationTopicArn: !GetAtt SnsSqsStack.Outputs.TaskAssignmentNotificationTopicArn
      Tags:
        - Key: Component
          Value: Cognito

Outputs:
  ApiUrlCognito:
    Description: API Gateway endpoint URL
    Value: !GetAtt CognitoStack.Outputs.ApiUrl
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !GetAtt CognitoStack.Outputs.UserPoolId
  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !GetAtt CognitoStack.Outputs.UserPoolClientId