AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Task Management System Backend - Main Template

Resources:
  CognitoStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: cognito-template.yaml
      Tags:
        - Key: Component
          Value: Cognito

  AuthHandlerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: auth-handler-template.yaml
      Parameters:
        UserPoolClientIdArn: !GetAtt CognitoStack.Outputs.UserPoolClientIdArn
        UserPoolArn: !GetAtt CognitoStack.Outputs.UserPoolArn
        TeamMemberSubscriptionStepFunctionArn: !GetAtt StepFunctionsStack.Outputs.TeamMemberSubscriptionStepFunctionArn
        TaskAssignmentNotificationTopicArn: !GetAtt SnsSqsStack.Outputs.TaskAssignmentNotificationTopicArn
      Tags:
        - Key: Component
          Value: AuthHandler

  SnsSqsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: sns-sqs-template.yaml
      Tags:
        - Key: Component
          Value: SNS-SQS

  StepFunctionsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: step-functions-template.yaml
      Parameters:
        TaskAssignmentNotificationTopicArn: !GetAtt SnsSqsStack.Outputs.TaskAssignmentNotificationTopicArn
        TaskDeadlineNotificationTopicArn: !GetAtt SnsSqsStack.Outputs.TaskDeadlineNotificationTopicArn
        ClosedTasksNotificationTopicArn: !GetAtt SnsSqsStack.Outputs.ClosedTasksNotificationTopicArn
      Tags:
        - Key: Component
          Value: StepFunctions

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !GetAtt AuthHandlerStack.Outputs.ApiUrl