Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: com.amalitechtaskmanager.handlers.auth.SignUpHandler
      CodeUri: C:\Users\NicholasOppong\Documents\Serverless Apps\task-manager-backend\TaskManager
      Runtime: java21
      Architectures:
        - x86_64