name: Deploy SAM Stack

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1
  STACK_NAME: task-manager
  ARTIFACT_BUCKET: task-manager-artifacts-${{ github.run_id }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: 'maven'

      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build SAM Application
        run: |
          cd TaskManager
          mvn clean package
          cd ..
          sam build

      - name: Create S3 Bucket for Artifacts
        run: |
          aws s3 mb s3://${{ env.ARTIFACT_BUCKET }} || true
          aws s3api put-bucket-versioning --bucket ${{ env.ARTIFACT_BUCKET }} --versioning-configuration Status=Enabled

      - name: Deploy SAM Application
        run: |
          sam deploy \
            --stack-name ${{ env.STACK_NAME }} \
            --s3-bucket ${{ env.ARTIFACT_BUCKET }} \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset \
            --parameter-overrides \
              Environment=prod

      - name: Cleanup Deployment Artifacts
        if: always()
        run: |
          aws s3 rb s3://${{ env.ARTIFACT_BUCKET }} --force || true